---
jobs:
- name: guarddog-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    trigger: true
  - task: run-tests
    file: dachs-cf-buildpack-guarddog/ci/unit-test/task.yml

- name: guarddog-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    trigger: true
    passed: [guarddog-tests]
  - put: acceptance
    params:
      repository: dachs-cf-buildpack-guarddog
  - task: run-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}

resources:
- name: dachs-cf-buildpack-guarddog
  type: git
  source:
    uri: https://github.com/DigitalInnovation/dachs-cf-buildpack-guarddog
    branch: master
- name: acceptance
  type: git
  source:
    uri: git@github.com:DigitalInnovation/dachs-cf-buildpack-guarddog.git
    branch: acceptance
    private_key: {{private-repo-key}}