---
jobs:
- name: unit-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    trigger: true
  - task: unit-tests
    file: dachs-cf-buildpack-guarddog/ci/unit-test/task.yml
    on_failure:
      put: slack-notify
      params:
        text: "unit-tests job failed! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/unit-tests"
        channel: {{slack-channel}}
        username: concourse
              
- name: script-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    trigger: true
    passed: [unit-tests]
  - task: script-tests
    file: dachs-cf-buildpack-guarddog/ci/script-test/task.yml
    on_failure:
      put: slack-notify
      params:
        text: "scrip-tests job failed! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/script-tests"
        channel: {{slack-channel}}
        username: concourse

- name: guarddog-integration-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    trigger: true
    passed: [script-tests]
  - task: run-integration-tests
    file: dachs-cf-buildpack-guarddog/ci/integration-test/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      CREATE_BUILDPACK: {{create_buildpack}}
    on_failure:
      put: slack-notify
      params:
        text: "guarddog-integration-tests job failed! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/guarddog-tests"
        channel: {{slack-channel}}
        username: concourse

- name: guarddog-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    trigger: true
    passed: [guarddog-integration-tests]
  - put: acceptance
    params:
      repository: dachs-cf-buildpack-guarddog
  - task: run-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
    on_success:
        put: slack-notify
        params:
          text: "guarddog-system-tests job passed! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/guarddog-system-tests"
          channel: {{slack-channel}}
          username: concourse
    on_failure:
        put: slack-notify
        params:
          text: "guarddog-system-tests job failed! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/guarddog-system-tests"
          channel: {{slack-channel}}
          username: concourse

- name: promote
  plan:
  - get: acceptance
    passed: [guarddog-system-tests]
  - put: stable
    params:
      repository: acceptance
    on_success:
        put: slack-notify
        params:
          text: "Guarddog promoted to stable branch! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/promote"
          channel: {{slack-channel}}
          username: concourse
    on_failure:
        put: slack-notify
        params:
          text: "Guarddog promote job failed! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/promote"
          channel: {{slack-channel}}
          username: concourse

resources:
- name: dachs-cf-buildpack-guarddog
  type: git
  source:
    uri: https://github.com/DigitalInnovation/dachs-cf-buildpack-guarddog
    branch: master
- name: acceptance
  type: git
  source:
    uri: git@github.com:DigitalInnovation/dachs-cf-buildpack-guarddog.git
    branch: acceptance
    private_key: {{private-repo-key}}
- name: stable
  type: git
  source:
    uri: git@github.com:DigitalInnovation/dachs-cf-buildpack-guarddog.git
    branch: stable
    private_key: {{private-repo-key}}
- name: slack-notify
  type: slack-notification
  source:
    url: {{slack-notify-webhook}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
