---
jobs:
- name: unit-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
  - task: unit-tests
    file: dachs-cf-buildpack-guarddog/ci/unit-test/task.yml
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: unit-tests job failed! :boom:\n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/unit-tests :construction:"
        channel: {{slack-channel}}
        username: concourse

- name: script-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [unit-tests]
  - task: script-tests
    file: dachs-cf-buildpack-guarddog/ci/script-test/task.yml
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: scrip-tests job failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/script-tests :construction:"
        channel: {{slack-channel}}
        username: concourse

- name: integration-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [script-tests]
  - task: run-integration-tests
    file: dachs-cf-buildpack-guarddog/ci/integration-test/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      CREATE_BUILDPACK: {{create_buildpack}}
      GIT_BRANCH: master
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: guarddog-integration-tests job failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/guarddog-tests :construction:"
        channel: {{slack-channel}}
        username: concourse

- name: python-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [integration-tests]
  - get: dachs-cf-buildpack-multi
    resource: buildpack-multi
    trigger: true
  - task: run-python-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/python/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      GIT_BRANCH: master
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: python system tests failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/python-system-tests :construction: "
        channel: {{slack-channel}}
        username: concourse

- name: ruby-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [integration-tests]
  - get: dachs-cf-buildpack-multi
    resource: buildpack-multi
    trigger: true
  - task: run-ruby-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/ruby/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      GIT_BRANCH: master
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: ruby system tests failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/ruby-system-tests :construction: "
        channel: {{slack-channel}}
        username: concourse

- name: timeout-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [integration-tests]
  - get: dachs-cf-buildpack-multi
    resource: buildpack-multi
    trigger: true
  - task: run-timeout-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/timeout/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      GIT_BRANCH: master
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: timeout system tests failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/timeout-system-tests :construction: "
        channel: {{slack-channel}}
        username: concourse

- name: concurrent-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [integration-tests]
  - get: dachs-cf-buildpack-multi
    resource: buildpack-multi
    trigger: true
  - task: run-concurrent-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/concurrent/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      GIT_BRANCH: master
    on_failure:
      put: slack-notify
      params:
        text: ":dachshund_snooty: :boom: concurrency system tests failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/concurrent-system-tests :construction: "
        channel: {{slack-channel}}
        username: concourse

- name: tests-complete
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: master
    trigger: true
    passed: [python-system-tests, ruby-system-tests, timeout-system-tests, concurrent-system-tests]
  - put: acceptance
    on_success:
        put: slack-notify
        params:
          text: "guarddog-system-tests job passed! \n Check: https://ci.dachs.dog/pipelines/guarddog"
          channel: {{slack-channel}}
          username: concourse
    on_failure:
        put: slack-notify
        params:
          text: ":dachshund_snooty: :boom: promotion to acceptance failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/tests-complete :construction: "
          channel: {{slack-channel}}
          username: concourse

- name: promote
  plan:
  - get: acceptance
    passed: [tests-complete]
  - put: stable
    params:
      repository: acceptance
    on_success:
        put: slack-notify
        params:
          text: "Guarddog promoted to stable branch! \n Check: https://ci.dachs.dog/pipelines/guarddog/jobs/promote"
          channel: {{slack-channel}}
          username: concourse
    on_failure:
        put: slack-notify
        params:
          text: ":dachshund_snooty: :boom: Guarddog promote job failed! :boom: \n :construction: Check: https://ci.dachs.dog/pipelines/guarddog/jobs/promote :construction: "
          channel: {{slack-channel}}
          username: concourse

- name: speculative-system-tests
  plan:
  - get: dachs-cf-buildpack-guarddog
    resource: speculative
    trigger: true
  - task: run-system-tests
    file: dachs-cf-buildpack-guarddog/ci/system-test/task.yml
    params:
      CF_API: {{cf_api}}
      APP_DOMAIN: {{app_domain}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      MULTI_BUILDPACK_URI: {{multi_buildpack_uri}}
      GD_BUILDPACK_URI: {{gd_buildpack_uri}}
      GIT_BRANCH: speculative

resources:
- name: master
  type: git
  source:
    uri: https://github.com/DigitalInnovation/dachs-cf-buildpack-guarddog
    branch: master
- name: acceptance
  type: git
  source:
    uri: git@github.com:DigitalInnovation/dachs-cf-buildpack-guarddog.git
    branch: acceptance
    private_key: {{private-repo-key}}
- name: stable
  type: git
  source:
    uri: git@github.com:DigitalInnovation/dachs-cf-buildpack-guarddog.git
    branch: stable
    private_key: {{private-repo-key}}
- name: speculative
  type: git
  source:
    uri: https://github.com/DigitalInnovation/dachs-cf-buildpack-guarddog
    branch: speculative
- name: slack-notify
  type: slack-notification
  source:
    url: {{slack-notify-webhook}}
- name: buildpack-multi
  type: git
  source:
    uri: https://github.com/DigitalInnovation/dachs-cf-buildpack-multi
    branch: master

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
