---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dan0young/dachs-cf-docker
    tag: latest

inputs:
- name: dachs-cf-buildpack-guarddog

run:
  path: ci/scripts/run-system-tests.sh
  dir: dachs-cf-buildpack-guarddog

params:
    CF_API:
    CF_USERNAME:
    CF_PASSWORD:
    CF_ORG:
    CF_SPACE:
    BUILDPACK_URI:
