---
cf_api: https://api.local.pcfdev.io
app_domain: local.pcfdev.io
cf_username: admin
cf_password: admin
cf_org: pcfdev-org
cf_space: pcfdev-space
cf_api_remote: https://api.run.pivotal.io
multi_buildpack_uri: https://bitbucket.org/cf-utilities/cf-buildpack-multi.git
gd_buildpack_uri: https://bitbucket.org/cf-utilities/cf-buildpack-fortification.git
ps_buildpack_uri: https://bitbucket.org/cf-utilities/cf-buildpack-process-supervisor.git
slack-notify-webhook: https://hooks.slack.com/services/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
slack-channel: platform-eng-team
create_buildpack: "true"
