#!/bin/bash

set -e

export TIMEOUT_SERVER=${TIMEOUT_SERVER:-60s}
export MAXCONN=${MAXCONN:-0}

PORT=3000 baz &

while ! nc -z localhost 3000; do
  sleep 0.2
done

nc -lku 3001 &

./haproxy -f haproxy.cfg &

wait -n

echo Terminating due to a child process exiting
